---
cache: 
  directories: 
    - ~/.npm
deploy: "provider:pages edge:true skip-cleanup:true keep-history:true github-token:$GITHUB_TOKEN local-dir:dist/ target-branch:gh-pages commit_message:\"Deploy Release\" on:branch:master"
git: "depth:3"
language: node_js
node_js: "-'12'"
script: 
  - "yarn build"