language:node_js
cache:
  directiries:
    - ~./ .npm
node_js:
  -'12'
git:
  depth:3
script:
  - yarm build
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_messages: "Deploy Release"
  on:
    branch: master
